apiVersion: v1
kind: ConfigMap
metadata:
  name: jds-ui-demo-nginx-conf
data:
  default.conf: |
    server {
      listen 80;

      root /srv/dist;
      index index.html;

      location /echo/ {
        alias /srv/dist/;
        try_files $uri $uri/ /echo/index.html;
      }

      location = /echo {
        return 301 $scheme://$http_host/echo/;
      }

      location / {
        try_files $uri $uri/ /index.html;
      }

    }
