apiVersion: v1
kind: ConfigMap
metadata:
  name: jds-ui-demo-nginx-conf
data:
  default.conf: |
    server {
      listen 80;

      root /srv/dist;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

    }
