apiVersion: apps/v1
kind: Deployment
metadata:
  name: jds-ui-demo
  labels:
    app: jds-ui-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jds-ui-demo
  template:
    metadata:
      labels:
        app: jds-ui-demo
    spec:
      serviceAccountName: workload-identity-jds-angular
      volumes:
        - name: staticfiles
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: jds-ui-demo-nginx-conf
            items:
              - key: default.conf
                path: default.conf
      initContainers:
        - name: data-localization
          image: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
          volumeMounts:
            - name: staticfiles
              mountPath: /srv
          env:
            - name: INIT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: jds-ui-demo-bucket
                  key: CLOUD_STORAGE_BUCKET
          command: [ "bash" ]
          args:
            - -c
            - >-
              mkdir -p /srv/dist &&
              gsutil -m cp -r "gs://$INIT_BUCKET/*" /srv/dist
      containers:
        - image: nginx:stable-alpine
          name: nginx-proxy
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-conf
              subPath: default.conf
              readOnly: true
            - mountPath: /srv
              name: staticfiles
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 6
