apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  jax.org/owner-team: TODO
  jax.org/owner-team-id: TODO
  jax.org/billing-group: TODO
  jax.org/system-group: jds-angular-ui
  jax.org/component: jds-angular-ui
  jax.org/component-id: TODO
  jax.org/component-tier: 3
  jax.org/grant-name: TODO
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  kind: Deployment
  create: true
