import { primitive } from '../src/lib/echo/primitive';
import { writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Generate Tailwind-compatible utility classes from Echo primitive colors.
 * These classes reference the CSS variables generated by the theme.
 */
function generateUtilityClasses(): string {
  const utilities: string[] = [
    '/**',
    ' * Auto-generated Echo Theme Utility Classes',
    ' * These classes match Tailwind\'s naming conventions and reference Echo CSS variables.',
    ' * Import this file if you want utility classes instead of inline styles with variables.',
    ' */',
    ''
  ];

  // Get all color names and shades
  const colorEntries = Object.entries(primitive).filter(
    ([_, shades]) => typeof shades === 'object' && Object.keys(shades).length > 0
  );

  // Generate text color utilities
  utilities.push('/* Text Colors */');
  for (const [colorName, shades] of colorEntries) {
    for (const [shade, _] of Object.entries(shades as Record<string, string>)) {
      utilities.push(`.echo-text-${colorName}-${shade} { color: var(--echo-${colorName}-${shade}); }`);
    }
  }
  utilities.push('');

  // Generate background color utilities
  utilities.push('/* Background Colors */');
  for (const [colorName, shades] of colorEntries) {
    for (const [shade, _] of Object.entries(shades as Record<string, string>)) {
      utilities.push(`.echo-bg-${colorName}-${shade} { background-color: var(--echo-${colorName}-${shade}); }`);
    }
  }
  utilities.push('');

  // Generate border color utilities
  utilities.push('/* Border Colors */');
  for (const [colorName, shades] of colorEntries) {
    for (const [shade, _] of Object.entries(shades as Record<string, string>)) {
      utilities.push(`.echo-border-${colorName}-${shade} { border-color: var(--echo-${colorName}-${shade}); }`);
    }
  }
  utilities.push('');

  // Generate fill color utilities (for SVGs)
  utilities.push('/* Fill Colors (for SVGs) */');
  for (const [colorName, shades] of colorEntries) {
    for (const [shade, _] of Object.entries(shades as Record<string, string>)) {
      utilities.push(`.echo-fill-${colorName}-${shade} { fill: var(--echo-${colorName}-${shade}); }`);
    }
  }
  utilities.push('');

  // Generate stroke color utilities (for SVGs)
  utilities.push('/* Stroke Colors (for SVGs) */');
  for (const [colorName, shades] of colorEntries) {
    for (const [shade, _] of Object.entries(shades as Record<string, string>)) {
      utilities.push(`.echo-stroke-${colorName}-${shade} { stroke: var(--echo-${colorName}-${shade}); }`);
    }
  }

  return utilities.join('\n');
}

// Generate and write the utility classes
const css = generateUtilityClasses();
const outputFile = join(__dirname, '../src/utilities.css');

try {
  writeFileSync(outputFile, css, 'utf-8');
  console.log(`✓ Generated utility classes at ${outputFile}`);
  console.log(`  Total size: ${(css.length / 1024).toFixed(2)} KB`);
} catch (error) {
  console.error('Error generating utility classes:', error);
  process.exit(1);
}
