name: 'Lint and Test Workflow'
on: workflow_call

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npx nx affected -t lint
      - name: Test affected
        run: npx nx affected -t test --configuration=ci
