name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Setup pnpm (optional, if you want a specific version not managed by corepack)
        uses: pnpm/action-setup@v3
        with:
          version: 10.13.1
          run_install: false

      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Lint affected
        run: pnpm run lint
      - name: Test affected
        run: pnpm run test --configuration=ci
      - name: Build affected
        run: pnpm run build
