name: Deploy JDS UI Demo
on:
  pull_request:
    branches:
      - 'main'
jobs:
  deploy:
    name: "Deploy Demo Application to GKE"
    uses: ./.github/workflows/_gcp_deploy.yml
    secrets: inherit
    with:
      environment: "jax-cluster-dev-10--dev"